# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: run pseudo command
          command: |
            echo run a build command here
            echo $(date +"%FT%T%z") | tee builded_time
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "04:aa:70:e5:2d:54:4f:e0:41:19:87:f0:61:b3:f9:6c"
      - run: rsync -av --delete . ${USER_NAME}@${HOST_NAME}:/home/ec2-user/circleci-test

# Orchestrate or schedule a set of jobs
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

